import { gradients } from './gradients';
const editorURL = 'editorPicks';
const topicsURL = 'topics';
const seriesURL = 'series';
export const editorPicksData = [
  {
    id: 1,
    title: 'Women Lectures',
    heading: 'Lectures about Women',
    description: 'Collection of lectures about women',
    image: '/woman165.png',
    playlistImage: '/young woman.jpg',
    url: editorURL,
    background: gradients.milkGradient,
  },
  {
    id: 2,
    title: 'Salat',
    heading: 'Salat is foundational',
    description: 'How the Prophet(S.A.W) prayed',
    image: '/salatcard.png',
    playlistImage: '/salatplaylist.png',
    url: editorURL,
    background: gradients.greyGradient,
  },
  {
    id: 3,
    title: 'Piety',
    heading: 'Piety is the way to Jannah',
    description: 'Some of the best collections on piety',
    image: '/piouscard.png',
    playlistImage: '/piousplaylist.png',
    url: editorURL,
    background: gradients.maroonGradient,
  },
  {
    id: 4,
    title: 'Lectures',
    heading: 'New amazing lectures',
    description: 'Some of the best by popular sheikhs',
    image: '/lecturescard.png',
    playlistImage: '/lecturesplaylist.png',
    url: editorURL,
    background: gradients.brownGradient,
  },
  {
    id: 5,
    title: 'Foreign',
    heading: 'Foreign Lectures',
    description: 'Collection of lectures from scholars abroad',
    image: '/foreign.png',
    playlistImage: '/foreignplaylist.png',
    url: editorURL,
    background: gradients.lightGreyGradient,
  },
];

export const seriesData = [
  {
    id: 1,
    title: 'Marriage',
    description: 'Series about marriage and relationships',
    image: '/marriagecard.png',
    url: seriesURL,
    heading: 'Marriages and Relationships',
    playlistImage: '/marriageplaylist.png',
    background: gradients.semiBlackGradient,
  },
  {
    id: 2,
    title: 'Hajj',
    description: 'Achieve Hajj Mabrooq',
    image: '/hajjcard.png',
    heading: 'Everything about Hajj',
    url: seriesURL,
    playlistImage: '/hajjplaylist.png',
    // background: gradients.lightGreenGradient,
    background: gradients.lightPurpleGradient,
  },
  {
    id: 3,
    title: 'Zakat',
    description: 'The fifth Pillar',
    image: '/zakatcard.png',
    url: seriesURL,
    heading: 'The Fifth Pillar',
    playlistImage: '/zakatplaylist.png',
    background: gradients.lightBrownGradient,
  },
  {
    id: 4,
    title: 'Muqabala',
    description: 'Debates amongst popular sheikhs',
    image: '/debatecard.png',
    url: seriesURL,
    heading: 'Insightful Debates',
    playlistImage: '/debateplaylist.png',
    background: gradients.yellowGradient,
  },
  {
    id: 5,
    title: 'Majlis',
    description: 'Outstanding talks from some sheikhs',
    image: '/majliscard.png',
    url: seriesURL,
    heading: 'Confrences and Dawah',
    playlistImage: '/majlisplaylist.png',
    background: gradients.lightBrownGradient,
  },
];

export const topicsData = [
  {
    id: 1,
    title: 'Tafseer',
    heading: 'Tafseer Collections',
    description: 'Tafseer collections ',
    image: '/ramadancard.png',
    url: topicsURL,
    playlistImage: '/ramadanplaylist.png',
    background: gradients.purpleGradient,
  },
  {
    id: 2,
    title: 'Hadith',
    description: 'Lectures on the prophet(S.A.W) deeds and instructions',
    image: '/hadithcard.png',
    url: topicsURL,
    heading: 'Hadiths of the Prophet',
    playlistImage: '/sahihmuslimplaylist.png',
    background: gradients.darkGreenGradient,
  },
  {
    id: 3,
    title: 'Seerah',
    description: 'The history and the life of prophet Muhammad(S.A.W)',
    image: '/seerahcard.png',
    heading: 'The life of Muhammad(S.A.W)',
    url: topicsURL,
    playlistImage: '/seerahplaylist.png',
    background: gradients.lightBrownGradient,
  },
  {
    id: 4,
    title: 'Fiqh',
    description: 'Know how to worship Allah',
    image: '/lawcard.png',
    url: topicsURL,
    heading: 'Islamic Jurispundence',
    playlistImage: '/lawplaylist.png',
    background: gradients.deepBlueGradient,
  },
  {
    id: 5,
    title: 'Aqeedah',
    description: 'Aqeedah is one of the fundamental aspects of deen',
    image: '/lightcard.png',
    url: topicsURL,
    heading: 'Aqeedah',
    playlistImage: '/lightplaylist.png',
    background: gradients.lightBlueGradient,
  },
];

export const sheikhData = [
  {
    id: 1,
    title: 'Garam da Gata',
    cover: '',
    owner: 'Sheikh Guruntumi',
    added: '12 days ago',
    duration: '3:12',
    album: 'Umdatul Ahkam',
  },
  {
    id: 2,
    title: 'Mace Mumina',
    cover: '',
    owner: 'Sheikh Jafar Adam',
    added: '12 days ago',
    duration: '5:12',
    album: "Nisa'ul Muminoon",
  },
  {
    id: 3,
    title: 'Gaskiyar Magana',
    cover: '',
    owner: 'Sheikh Ibrahim Maqari',
    added: '11 days ago',
    duration: '2:10',
    album: 'Lecture',
  },
  {
    id: 4,
    title: 'Muhimmancin iyaye',
    cover: '',
    owner: 'Sheikh Ibrahim Daurawa',
    added: '10 days ago',
    duration: '7:00',
    album: 'Riyadul Saleeheen',
  },
  {
    id: 5,
    title: 'Ya ake gyara zuciya',
    cover: '',
    owner: 'Sheikh Ibrahim Mansoor',
    added: '7 days ago',
    duration: '6:12',
    album: 'Muhadara',
  },
  {
    id: 6,
    title: 'Hadisai Ingantattu',
    cover: '',
    owner: 'Sheikh Sherif Saleh',
    added: '9 days ago',
    duration: '5:19',
    album: 'Ramadan Tafseer',
  },
];
